spring.application.name=esenciavainilla
# ── Conexión a PostgreSQL ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/esenciaVainilla
spring.datasource.username=postgres
spring.datasource.password=juan40534
spring.datasource.driver-class-name=org.postgresql.Driver

# ── Pool de conexiones (HikariCP, incluido por defecto) ───────
spring.datasource.hikari.maximum-pool-size=5

# ── Para ver las queries en consola (útil en desarrollo) ──────
logging.level.org.springframework.jdbc.core=DEBUG
